name: Cricket Ninja
favicon: null
layout_spectrum: 0.7197507326491177
typography_spectrum: 0.17980539123527706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8894540334586054
  lightness: 0.8342777017969638
  saturation: 0.2101810108870268
  rhythmicContrast: 0.6768495582509786
purpose: []
